name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=3.5.3
  - python=3.7.7
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - pip
  - pip:
    - plotly 
    - pandas
    - matplotlib
    - scikit-learn
    - numpy
